name: docs

on:
  push:
    branches: [main, dev]
    paths:
      - '**/*.md'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [main]
    paths:
      - '**/*.md'
      - '.github/workflows/docs.yml'
  schedule:
    - cron: '11 21 * * 5'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Check Markdown links
        uses: lycheeverse/lychee-action@v2.9.0
        with:
          args: '--verbose --no-progress --exclude-mail **/*.md'
          fail: true
